### ISSUE TITLE
Impossible to run any build correct

### ISSUE THREAD

**Issue by Javlopez** [semaphoreci-demos/semaphore-demo-ruby-kubernetes#14]
I tried to run the default  repo https://github.com/semaphoreci-demos/semaphore-demo-ruby-kubernetes but nothing works lost several minutes trying to works but nothing happens.

The errors says:
```bash
Running: ssh-keyscan -p 29920 -H 195.201.55.114 >> /home/semaphore/.ssh/known_hosts && ssh-add /home/semaphore/.ssh/semaphore_cache_key
# 195.201.55.114:29920 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2
# 195.201.55.114:29920 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2
# 195.201.55.114:29920 SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2
Identity added: /home/semaphore/.ssh/semaphore_cache_key (/home/semaphore/.ssh/semaphore_cache_key)
checkout
Performing shallow clone with depth: 50
HEAD is now at 0def91a Update Dockerfile
cache restore
==> Detecting project structure and fetching cache.

* Detected Gemfile.lock.
* Fetching 'vendor/bundle' directory with cache keys 'gems-master-04e39b496b067454c87f7ac50b548942,gems-master-,gems-master-'.
MISS: gems-master-04e39b496b067454c87f7ac50b548942
MISS: gems-master
MISS: gems-master
bundle install --deployment --path vendor/bundle
[1mTraceback[m (most recent call last):
	2: from /home/semaphore/.rbenv/versions/2.5/bin/bundle:23:in `<main>'
	1: from /home/semaphore/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
/home/semaphore/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': [1mCould not find 'bundler' (1.17.2) required by your /home/semaphore/semaphore-demo-ruby-kubernetes/Gemfile.lock. ([1;4mGem::GemNotFoundException[m[1m)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
[mexport SEMAPHORE_JOB_RESULT=failed
```

This example should be running fine, but unfortunately no.

Any ideas?

**Comment by TomFern** [comment]
Hello @Javlopez. Thank you for reporting this. I updated bundler, among other dependencies and it's working for me now. Give it another try and let me know please.
